version: '3.6'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - regenfass

  

networks:
  regenfass:
    name: regenfass
    driver: bridge

