version: '3.6'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - regenfass

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana-development
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - GF_DEFAULT_INSTANCE_NAME=my-instance
      - GF_SECURITY_ADMIN_USER=isaui
      - GF_SECURITY_ADMIN_PASSWORD=isacitrabuana1717
      - GF_LOG_MODE=console
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - regenfass

networks:
  regenfass:
    name: regenfass
    driver: bridge

