name: Build and Test with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged
        ports:
          - 3000:3000
          - 8080:8080
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: isaui
          password: Babiharam17

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v1.5.1

      - name: Build and run Docker services
        run: docker-compose up --build -d

      - name: Stop Docker services
        run: docker-compose down

