on:
    push:
    pull_request:
      
jobs:
    deploy:
      concurrency:
        group: "${{ github.ref_name }}"
        cancel-in-progress: true
      runs-on: ubuntu-latest
      steps:
        - name: Install and configure the Koyeb CLI
          uses: koyeb-community/install-koyeb-cli@v2
          with:
            api_token: "38f6iiwgprarmrupefuai4a1fu3j0hvfqe3xizk2yrb8gjzqgwpjlzhn17amqsce"
            
        - name: Check out the Git repository
          uses: actions/checkout@v4
  
        - name: Set up Java toolchain
          uses: actions/setup-java@v4
          with:
            distribution: "temurin"
            java-version: "21"
            cache: "gradle"
        
        - name: Set execute permission on gradlew
          run: |
            chmod +x gradlew
        
        - name: Run build
          run: ./gradlew clean build
    
        - name: Build and deploy the application
          uses: koyeb/action-git-deploy@v1
          with:
            app-name: docker-compose-capek
            service-ports: "2000:http"
            service-routes: "/:2000"
            git-builder: docker
            git-docker-dockerfile: Dockerfile.koyeb
            privileged: true
            skip-cache: true
  